### ISSUE TITLE
add vars.yml

### ISSUE THREAD

**Issue by ivotron** [systemslab/sirius-popper#2]
* [ ] read monitor, osd and client roles for containers from files written at setup time
  * [ ] read monitor IP address and CIDR from file too
  * [ ] define variable with list of devices
  * [ ] add `conceptual` to get bisection bandwidth
  * [ ] add `fio` to get 4MB seq write bandwidth and 4k random read
  * [ ] add `radosbench` item with equivalent options: 

    ```yaml
    image: your/ceph:image
    privileged: true
    pid: host
    network_mode: host
    environment:
      OSD_DEVICES: '{{ osd_devices }}'
    volumes:
    - '/dev:/dev'
    ```
